baseURL = "https://zishuoblog.netlify.app"
locale = "zh-cn"
title = "zishuo的博客"
theme = "paper"

[params]
  avatar = "/avatar.png"
  name = "zishuo"
  bio = "欢迎访问我的博客！"
  github = "zishuo2002"
  email = "zzs15222867873@163.com"
