baseURL = "https://zishuoblog.netlify.app"
locale = "zh-cn"
title = "zishuo的博客"
theme = "paper"

[params]
  avatar = "https://github.com/zishuo2002.png"
  name = "zishuo"
  bio = "欢迎访问我的博客！"
  github = "zishuo2003"
  math = true
